### ISSUE TITLE
Import error when attempting to run local install or docker image on cloud instance

### ISSUE THREAD

**Issue by pspur** [raonyguimaraes/mendelmd#27]
Executing `python manage.py migrate` causes error `ImportError: No module named 'scripts.worker'`. 

In looking for the location of that module, it seems like the source is included in .gitignore: `scripts/worker.py`

**Comment by raonyguimaraes** [comment]
Hi pspur,

This should be fixed now, can you try to pull or clone the repository again?

Thank you!
