### ISSUE TITLE
Variants are not classified by Functional Class

### ISSUE THREAD

**Issue by natalia-linhares** [raonyguimaraes/mendelmd#36]
I would like to check how many variants in my patients are missense, nonsense and silent. However, the variants are not classified by Functional Class in the Dashboard/Individual.

**Comment by raonyguimaraes** [comment]
This bug has been sorted out on commit 4eefc97c0a5f167a7726ea943ec4583eb9b39199!

![image](https://user-images.githubusercontent.com/124987/55442590-2e86db00-55a7-11e9-82ec-ea6665094f83.png)

**Comment by natalia-linhares** [comment]
For me it is still not working...

Could you ckeck it, please?

![image](https://user-images.githubusercontent.com/38384725/55477940-be9d4280-55f0-11e9-9830-e9af1bb1a952.png)

**Comment by raonyguimaraes** [comment]
Hi there, you just need to repopulate your individuals. I will do that for you!

**Comment by natalia-linhares** [comment]
Ok! Now it is working! Thanks!

**Comment by tiagoslg** [comment]
solved
