### ISSUE TITLE
Remove .vcf from test server

### ISSUE THREAD

**Issue by njspix** [raonyguimaraes/mendelmd#38]
Hello @raonyguimaraes,

I would like to remove a .vcf file from the test server. Can you please assist me with this?

Thanks,
Nathan Spix

**Comment by EricS87** [comment]
@njspix Did raonyguimaraes remove your files for you or instruct you how to remove them? I am having same issue.

**Comment by njspix** [comment]
I was able to reach him through LinkedIn and he removed the file.

**Comment by raonyguimaraes** [comment]
Hi there just to confirm that yes I can remove any vcf that you would want to be removed.
