### ISSUE TITLE
Please remove vcf files

### ISSUE THREAD

**Issue by EricS87** [raonyguimaraes/mendelmd#43]
@raonyguimaraes I uploaded vcf files, before creating an account, on October 9, 2022 and I can't find a way to delete them. Please help remove them. Thank you

**Comment by raonyguimaraes** [comment]
Can you please let me know the sample ids?

**Comment by EricS87** [comment]
@raonyguimaraes 
Sample IDs: 9390, 9391, 9392, and 9393. 

Thank you

**Comment by raonyguimaraes** [comment]
I confirm I deleted all 4.
